spring:
  application:
    name: application-gateway-dev
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-management-service
            uri: lb://user-management-service-dev
            predicates:
              - Path=/api/v1/users/**
              - Path=/api/v1/auth/**

          - id: product-service
            uri: lb://product-service-dev
            predicates:
              - Path=/api/v1/products/**

          - id: order-service
            uri: lb://order-service-dev
            predicates:
              - Path=/api/v1/orders/**

          - id: discovery-server
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/

          - id: discovery-server-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
server:
  port: 8090

