spring:
  application:
    name: user-management-service-dev
  datasource:
    url: jdbc:postgresql://localhost:4001/user_mgt_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true

server:
  port: 8081
